### ISSUE TITLE
Homework page is broken

### ISSUE THREAD

**Issue by acacheung** [svbazarian/svbazarian.github.io#2]
http://svbazarian.github.io/homework/ comes up with a 404 because of Web Work folder

**Comment by svbazarian** [comment]
Hi Amanda,

I see the error but I'm a little confused about how to fix it. I don't know
if it's something you can help me with here or if you'd rather just show me
in class. Thanks!

**Comment by acacheung** [comment]
Hi - It's because of the root "Web Work" folder that all the other folders are inside of. Removing the "Web Work" folder and bringing all the other folders back out to root should fix the issue
